### ISSUE TITLE
폰트 맑은 고딕화 현상

### ISSUE THREAD

**Issue by 2ne1ugly** [ImBada/Aseprite-Korean#2]
운영체제는 Windows 11입니다. ttf 미리보기에서는 다음과 같고요,
![image](https://user-images.githubusercontent.com/47616772/143901369-e1d92aec-8b38-4ce9-93a9-195c9f9d5c1b.png)

프로그램 내부에서는 이렇게 표시됩니다
![image](https://user-images.githubusercontent.com/47616772/143901484-12e2faac-2a40-497b-b94a-50c4e63d3896.png)

macOS Big Sur 기준으로는 정상적으로 표시되는 것 같습니다.

**Comment by ImBada** [comment]
폰트 조만간 변경이 필요할 거 같습니다..
