### ISSUE TITLE
다른 확장 도구와의 충돌?

### ISSUE THREAD

**Issue by x2A03** [ImBada/Aseprite-Korean#4]
혹시나 해서 문의 드려봅니다

https://bitbucket.org/jjhaggar/aseprite-dithering-matrices/src/master/

저만 그런진 모르겠으나 위 확장 도구를 설치하면 한글 번역은 제대로 나오나 테마가 깨져서 글씨가 뭉개지고 잘립니다

1.3 베타 버전으로 쓰다가 오류가 나서 1.2 버전으로 돌아왔는데도 그대로라 이것의 영향이 있는 것 같기도 합니다...
테마를 지웠다 다시 깔아도 변하는 게 없네요 브러시가 저장되는지 여부를 몰라 에이스프라이트 자체는 삭제 후 재설치를 안 해본 상태입니다
1.3 버전 대응이 나올 때까지 기다릴 것 같습니다 이후에도 문제가 생기면 추가하겠습니다...

**Comment by ImBada** [comment]
최근에 버전 갱신을 많이 안 해서 그럴 수도 있는데 조만간 갱신하겠습니다

**Comment by x2A03** [comment]
앗 처음에 당황해서 글을 썼는데 이것저것 만지다 보니 충돌이 생기는 것과는 별개로 한글 테마 이슈는 해결했습니다 간단한 문제였는데 제가 체크를 못 했네요 항상 감사합니다!

**Comment by ImBada** [comment]
확인 감사합니다
